server:
  port: 8181

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到Eureka Server，默认为true
    fetch-registry: false #是否从Eureka Server获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 5000 #清理无效服务间隔（单位毫秒，默认是60*1000）

logging:
  config: classpath:logback-spring.xml
