server:
  port: 8080

spring:
  application:
    name: gateway
  #    开启动态路由，默认：http://gateway_ip:port/SERVICE_APPLICETION_NAME/请求路径；其中服务名默认大写
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #          这里吧上面访问服务的SERVICE_APPLICETION_NAME改为小写
          lower-case-service-id: true
      #      默认路由交给hystrix，提供熔断功能
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            #   熔断后降级接口
            fallbackUri: forward:/fallback


#设置hystrix熔断时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1500



eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 #eureka client发送心跳给server端的频率（默认30秒）
    lease-expiration-duration-in-seconds: 10 #eureka client发送心跳给server端后，续约到期时间（默认90秒）
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone:  http://localhost:8181/eureka/
    registry-fetch-interval-seconds: 3 #client间隔多久去拉取服务注册信息（默认30秒）对于api-gateway如果要迅速获取服务注册状态，可以缩小该值

logging:
  config: classpath:logback-spring.xml